### ISSUE TITLE
Only the color of the last feature change.

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1168]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.118.30769 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3b620b713e24c9637db8ea6ad1f1ee88ef13367a
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US) 

For example, only the color of the pad changes in a given file. I think the rest of the things connected with it should also change color. I also changed the color of pad2, only the color of the pad changed, Not the color of things connected to it.   

[mp4.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8369946/mp4.zip)  
 
[File.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8369951/File.zip)

**Comment by bambukouk** [comment]
AFAIK this is the standard FreeCAD behaviour (nothing to do with Link branch).
I normally set body colour not the individual features etc.
Although you can change appearance of the body's feature it doesn't affect final body appearance and is only apparent when the specific feature is the only one visible.

Can't open your file because I am on Linux appimage (so different OCC)
