### ISSUE TITLE
The shortcut key is not working (note: Outside the draft workbench) 

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1184]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.402.26244 +4679 (Git)
Build type: Release
Branch: LinkDaily
Hash: 2ed36c0a234b3871a790ac8437f496f29e025ded
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)

The move to group key (Shift+G) only works in the draft workbench. In the old version, this key also worked outside the draft workbench. Previously, this key worked in all workbenches. 

![1](https://user-images.githubusercontent.com/92737149/161935538-15ee9c5e-8cfd-4f61-873d-accf03a0711e.jpg)

**Comment by realthunder** [comment]
This can actually be considered as a bug that's been fixed in recent release. The workbench specific command and its shortcut is only supposed to be active if it is visible in either toolbar or menu bar. This is so that user can assign the same shortcut to different command in different workbench. If you really want some command to be available globally, you can create your own global toolbar with that command.

![image](https://user-images.githubusercontent.com/1207888/161936840-22aeeb47-2e8c-48a9-8722-2ec38d7263fc.png)

**Comment by hamza00789** [comment]
Thanks for the quick reply.
