### ISSUE TITLE
When using Axial alignment constraint things do not behave as expected

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1208]
Simple assembly.
Box with a round hole and round peg.
Two cylindrical faces used as elements.

![ax_al_test1](https://user-images.githubusercontent.com/50301871/163593879-0072e491-c14f-47a5-ac34-2f39054cc818.png)

```
OS: elementary OS 6.1 JAlnir (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)
```

File:
[axial_alignment_test.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8496877/axial_alignment_test.FCStd.zip)

but... when I try to use `Axial Alignment constraint` things do not behave as expected?
i.e.
![ax_al_2](https://user-images.githubusercontent.com/50301871/163594325-99523484-1096-4e35-9384-0fe6fafb5222.png)

instead of:

![like_so](https://user-images.githubusercontent.com/50301871/163594587-ee625393-65cb-44fa-b81a-04428ec270d5.png)

What am I doing wrong, please?

**Comment by realthunder** [comment]
I can reproduce the problem. It may fail or not depending on whether to select the box face first or the cylinder face. And when it is not moved correctly, there may either be warning message about redundant constraint or error message about inconsistent constraint. I think the problem is caused by the initial position of the parts being too far apart, and the solver is confused about what message to output. As a general 'solution' to this kind  of problem, just manually move the parts a bit closer.

**Comment by bambukouk** [comment]
Thank you for the confirmation.
That was my understanding as well, but I was beginning to doubt my sanity after questions on the subject on main forum.
