### ISSUE TITLE
Tutorial error: Document.cpp(331) cannot edit object Assembly not found in document

### ISSUE THREAD

**Issue by poleguy** [realthunder/FreeCAD_assembly3#149]
I tried to run the tutorial on Preview 0.8.6 on Windows, and when you try to move the cubes within the linked assembly they don't move but spit out an error:
"Document.cpp(331) cannot edit object Assembly... not found in document..."

https://github.com/realthunder/FreeCAD_assembly3/wiki/Common-Operations

How stale is the 0.8.6 windows binary? Might this be fixed in the source already? Does the tutorial work on the latest source?

**Comment by ceremcem** [comment]
> Does the tutorial work on the latest source?

I can confirm that those tutorials (and more) are working on the latest source on Linux. Moreover, there are lots of changes since 0.8.6 in the source. @realthunder is preparing a new release nowadays. You can wait for that or compile from source (which I think compiling from source has lots of advantages).

...or, @realthunder will comment this to point out the exact issue.

**Comment by realthunder** [comment]
This is indeed a bug. Thanks for reporting. It only happens if owner assembly of the moving part is external linked. In default cases, the part mover moves part in context of the top level assembly, which is usually not external linked. I guess that's why the problem is hidden for so long. I'll fix it soon.
