### ISSUE TITLE
body multiple solid basefeature pocket confusion

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD_assembly3#198]
I think this has to do with multiple solids and basefeature in partdesign.
Try to though all Pocket003. But where is the pocket?
![gears_troughall](https://user-images.githubusercontent.com/11283066/53175459-481e2580-35ec-11e9-9a9e-f598bf8254b8.png)
[gears_pad_error.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2889630/gears_pad_error.zip)

**Comment by dulouie** [comment]
When i make the pocket on every single solid first and fuse them later together. I get these nice shape:)
![niceshape](https://user-images.githubusercontent.com/11283066/53176425-52d9ba00-35ee-11e9-9245-a48d472e4991.png)

**Comment by realthunder** [comment]
I don't think this is related to multi solid feature. It seems OCCT has trouble with cutting the _not so valid boolean shape_. The root cause of this problem is that the involute gear uses BSpline for the teeth, and therefore the resulting _flat_ face is not really flat to OCCT. When you fuse the two involute gears by touching their _not so flat_ faces, you actually get two solids. With upstream FC you'll probably notice this as the result will be missing one gear. To correct the problem, just make these two gears touch a bit more, say, `InvoluteGear002.Placement.Base.Z = 17.999`.

BTW, with these non-flat faces, it is not advisable to map sketch on it. You get noticable slow down, and may probably get broken shape somewhere along the way. Use datum plane instead.

Another thing, just like fusing, it is also advisable to have some leeway for pocketing as well. So the datum plane should be slightly above the gear face.

**Comment by dulouie** [comment]
Okay thanks for the explanation.
