### ISSUE TITLE
Building slvs

### ISSUE THREAD

**Issue by maidenone** [realthunder/FreeCAD_assembly3#23]
according to the wiki:
```
cd asm3
git submodule update --init slvs

```
but i found that i always ended up in detached state..
```
maiden@horse:~/projects/FreeCAD_assembly3/slvs/build$ git branch
* (HEAD detached at 665f4a6)
  python

```
running cmake would result in:
```
cmake -DBUILD_PYTHON=1 ..
CMake Error at cmake/GetGitCommitHash.cmake:8 (file):
  file failed to open for reading (Not a directory):

    /home/maiden/projects/FreeCAD_assembly3/slvs/.git/HEAD
```

running `git checkout python` after submodule update resolved this issue for me.

**Comment by ceremcem** [comment]
Isn't that normal? I think it's a git related question. I frequently use submodules in my projects and if you clone a project somewhere else and update the the submodule, submodule is checked out to the point it was committed to the main project. That's why you will be end up with detached state. You are always have to checkout the intended branch for submodules manually.

**Comment by realthunder** [comment]
The detached state is normal for submodule. However, SolveSpace cmake file requires a normal git repo in order to get the latest commit hash. It cannot handle a submodule, which stores .git directory in the parent. See [here](https://github.com/realthunder/solvespace/blob/665f4a65a3bc57abc13335c787bf5033394baa42/CMakeLists.txt#L20) for an explanation.

**Comment by ceremcem** [comment]
@realthunder It's kind of interesting. They should perfectly be able to get the commit hash from a submodule.

**Comment by ceremcem** [comment]
@maidenone You may try out FreeCAD-Asm3 builder scripts: https://github.com/ceremcem/build-freecad-asm3

**Comment by timmwille** [comment]
I guess this holds valuable info in #279 and can be treated as one as well as #1?

**Comment by ceremcem** [comment]
Also related: https://github.com/realthunder/FreeCAD_assembly3/issues/363#issuecomment-737404792

**Comment by luzpaz** [comment]
Can this ticket be closed?
