### ISSUE TITLE
How to perform assembly based modeling?

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#25]
I need to cut the front panel of the enclosure to be able to plug the ethernet and usb cables, so I want to trigger appropriate cuts on the `front-panel` by moving it towards the device:

![cut-front-panel](https://user-images.githubusercontent.com/6639874/43788793-03b71e26-9a77-11e8-91a6-f95f6cf43d09.gif)

I even don't know the name of the operation but I think it's somehow related with assembly stage. Because when I define the cutting pattern and then move the electronic component, the cutting pattern should track the electronic part's movement. 

Anyway, what is the name of the operation (so I could find some documentation about it) and if it is related with assembly, how can we do this in asm3?

**Comment by realthunder** [comment]
I don't think there is such a high level operation in FC right now. I know Path workbench can probably generate an offseted silhouette shape. Can you please attach the file here so that I can play around?

**Comment by ceremcem** [comment]
The model in above screencast is here: https://github.com/ceremcem/fc-asm3-test/tree/use-detailed-rpi I'm taking a look at the Path workbench.

**Comment by dulouie** [comment]
Hey guys, there is already such a high level operation in freecad, the realthunder sub-shapebinder.
Look at my screencast and don't worry about computation time.

![raspberry_shapebinder](https://raw.githubusercontent.com/dulouie/screencast/master/raspberry_shapebinder.gif)


@realthunder I used your new 0.8 release and the sub-shapebinder is not yellow anymore, he takes the color from his parent. And this operation doesn't work inside an assembly3 container. It gives "Cyclic dependency  error" with the own object or as a link. So i have to set the placement with asm3 constraints and then put it outside of the asm3 container to use the shaperbinder. 

[raspberry_shapebinder.fcstd](https://github.com/dulouie/screencast/blob/master/raspberry_shapebinder.fcstd?raw=true)

**Comment by realthunder** [comment]
@dulouie using shapebinder is great. I was thinking that @ceremcem was asking how to create the cut shape. If the component is mostly regular shape like these, then using sketch makes much more sense. You can use shapebinder in assembly, but you need to be careful about the shape reference. I'll make a tutorial about this.

**Comment by ceremcem** [comment]
@dulouie Wuuuu-huuu! That's what I wanted! Thanks!

**Comment by realthunder** [comment]
@ceremcem @dulouie Checkout the two screen casts here. There are two ways to use the sub-shapebinder, [with Part WB](https://raw.githubusercontent.com/wiki/realthunder/FreeCAD_assembly3/images/part-binder.gif), or [with PartDesign WB](https://raw.githubusercontent.com/wiki/realthunder/FreeCAD_assembly3/images/partdesign-binder.gif).

I'll publish a tutorial in Assembly3 wiki later. Here is brief description, when using Part Cut operation to cut the hole, you must add the Base shape, as well as the resulting Cut shape to the assembly. And, you must constraint the base shape, **NOT** the cut shape against the pcb part. These steps are a bit _unnatural_, so to speak. The advantage is that the cut shape is updated automatically when the constraint changes, while in PartDesign approach, you have to double click the binder to manually update it every time the panel body changes position.

**Comment by realthunder** [comment]
You can find the tutorial [here](https://github.com/realthunder/FreeCAD_assembly3/wiki/Modeling-using-Assembly)

**Comment by dulouie** [comment]
THX for the tutorial!

**Comment by ceremcem** [comment]
I did follow the tutorial several times and I have very different results for each. Although it did work on my actual drawing, I wanted to prepare a reference project from scratch (https://github.com/ceremcem/fc-asm3-cut-window/) and a more detailed HOWTO, but I can't proceed after step "drawing the cutting path".

The main difference from the original tutorial is that, in a real-world usage, you would either get the model in STEP format by a third party or you would have the model drawn beforehand and then specify the cut. So, 

1. I prepared the `device` with asm3 which holds `pcb` and the `connector`
2. I prepared the `enclosure` (the end product) which holds the `device` and the `panel`. 
3. Then I wanted to cut the window. 

In [this model](https://github.com/ceremcem/fc-asm3-cut-window/tree/42d5aaaf3b30534462aa5651e73b691a0a195c83), when I try to draw the cutting path, it is placed far far away: 

![cutting-path-bug](https://user-images.githubusercontent.com/6639874/44006584-8ffb4468-9e8f-11e8-935b-3356e477755c.gif)

**Comment by realthunder** [comment]
There are two way to create sketch, one from the Sketch workbench, the other is from PartDesign. In your case, you should use the PartDesign, simply double click the body in the tree view to activate the body and got the PartDesign workbench, click the sketch toolbar button there.

You are trying something very advanced in FC, yet you appear to be not very familiar with the PartDesign concepts. PartDesign body is like assembly container, which has its own coordinate system. When add some object inside, the object will jump in 3D view because of the new coordinate system. I suggest you use my first Part workbench approach first, and avoid construct your model using PartDesign Body. 

Whatever approach you choose, it is better to construct your parts first without add them to the (final) assembly container. As shown in my tutorial, I only add the parts when they are ready. You can test the effect of panel cut update by manually move the socket.

**Comment by realthunder** [comment]
> The main difference from the original tutorial is that, in a real-world usage, you would either get the model in STEP format by a third party or you would have the model drawn beforehand and then specify the cut.

Forgot to reply on this. Yes I am aware of this common use case, which is why in both of my approach the cut extrusion is generated the same way, which should fit if the socket is a STEP import.

Can you attach your file here? If you socket is a STEP import, then the sketch is better to be created using the sketch  workbench. You either create the sketch before adding the socket to any container (which is the preferable way), or create the sketch later (which will appear out of place when you finish editing), and then drag it to the container.

**Comment by ceremcem** [comment]
This is my howto: https://github.com/ceremcem/fc-asm3-cut-window
