### ISSUE TITLE
Upstream saved files are losing geometry on recompute (opening in this fork)

### ISSUE THREAD

**Issue by akamensky** [realthunder/FreeCAD_assembly3#372]
Using nightly releases opening (open-source copy of) MGN12H block model in upstream shows correct model:

<img width="941" alt="Screen Shot 2020-12-06 at 2 01 07 PM" src="https://user-images.githubusercontent.com/985805/101272926-bc2ebb00-37cb-11eb-9cde-69570ffc8bab.png">

Opening the same model in this fork produces invalid model (after forced recompute):

<img width="937" alt="Screen Shot 2020-12-06 at 1 59 12 PM" src="https://user-images.githubusercontent.com/985805/101272934-d1a3e500-37cb-11eb-876d-fc106a4db748.png">

Model in question https://www.thingiverse.com/thing:4249218/files

**Comment by realthunder** [comment]
With the above referenced commit, the behavior should now be the same as upstream. After recompute, you'll see the hole shrink, which may be caused by recent change in PartDesign hole feature in upstream. If you open the file in upstream, and mark the whole document for recompute, you'll see the same shrinking behavior. The reason for recompute in my image is for generating new topo names.

I'll make a new release soon.

**Comment by luzpaz** [comment]
@realthunder can this ticket be closed ?
