### ISSUE TITLE
Moving objects into and out of assembly container causes unintentional displacement

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#39]
I'm trying to create a `Binder` for a shape. 

* I'm clicking the shape, 
* clicking the "PartDesign/Sub-Shape Binder" 
* this generates the `Binder
* I move the binder 1 level out of its current hierarchy
* Placement of `Binder` changes unintentionally

![part-binder-offset](https://user-images.githubusercontent.com/6639874/44916796-41021300-ad3f-11e8-8ba5-972f78bf5049.gif)

Model: [test2.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2340301/test2.zip)

**Comment by ceremcem** [comment]
This is not specific to the binder, it can also be observed on normal objects dragged out of container: 

![offset-error](https://user-images.githubusercontent.com/6639874/44917512-35175080-ad41-11e8-8a5d-55c89b36c89e.gif)

**Comment by realthunder** [comment]
This is expected. The final position of an object in 3D view is determined by the accumulated placement of the object and all its containers. When you drag and drop the object, its parent changes, hence its 3D view position changes as well.

**Comment by ceremcem** [comment]
Objection: While it's completely required by design to calculate objects' positions relatively, "dragging and dropping an object into another container" would never be performed with the intention of position change, the "drag and drop" event must never change the objects position. 

### Proposal 

When an object is dropped into or out of a container, its own placement should be recalculated regarding the container it's dragged into or out of and then overwritten. This will still satisfy the relative calculation requirement and also let us group some objects with a new Assembly container in the middle of the  design process, change their position by moving the new Assembly container and then take them out of the container without breaking any previous valuable placement adjustments.

**Comment by easyw** [comment]
> Proposal
When an object is dropped into or out of a container, its own placement should be recalculated regarding the container it's dragged into or out of and then overwritten. This will still satisfy the relative calculation requirement and also let us group some objects with a new Assembly container in the middle of the design process, change their position by moving the new Assembly container and then take them out of the container without breaking any previous valuable placement adjustments.

This should be an option IMO. In many cases it is useful to drag an object inside a container and let the object get the placement multiplied by the container. So if this behavior is going to change, it would be nice to have an option to keep the old one when dragging in/out objects.

**Comment by realthunder** [comment]
@ceremcem I have just added this feature in my LinkStage3 branch. Since you are very active in testing my branch, it is better for you to use your own build to test the latest feature and fix. To activate the feature, right click anywhere in the tree, select `Tree options->Sync placement`.

**Comment by ceremcem** [comment]
I was about to say that [I'm able to build LinkStage3 from source for a while with a virtual machine](https://github.com/ceremcem/build-freecad-asm3), so, anyway, here we are: 

![image](https://user-images.githubusercontent.com/6639874/44955452-5d778a00-aebc-11e8-9b5b-bbf1507c167f.png)

It seems a permanent setting, which is great.

**Comment by ceremcem** [comment]
This feature works, thank you!

**Comment by ceremcem** [comment]
# Version 
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14961 (Git)
Build type: Unknown
Branch: LinkStage3
Hash: 0f69c9bfb3a9959e284565576cc5780eafe6fcea
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

# File 

[test2.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2343494/test2.zip)

# Description

Starting over, here I have two components and I will cut the `panel` according to sockets: 

![image](https://user-images.githubusercontent.com/6639874/44957666-ffa76a00-aedc-11e8-88d1-9ef3fe7ac8f4.png)

## Make the socket cuts 

I'm creating a solid which describes the windows to be cut: 

![propertylinksublist-does-not-support-external-object](https://user-images.githubusercontent.com/6639874/44957685-4a28e680-aedd-11e8-8a32-2237c1908f0c.gif)

It seems it's not supported explicitly, so I need to go to parent object and create the shape: 

![create-sketch-only-in-original](https://user-images.githubusercontent.com/6639874/44957818-44340500-aedf-11e8-811f-74d9cd8aca4a.gif)

## Cut the panel by using `front-panel-cuts`

Exception arises: 

```
<type 'exceptions.AttributeError'>: 'App.Document' object has no attribute 'Extrude'
```
![no-attribute-extrude](https://user-images.githubusercontent.com/6639874/44957833-82c9bf80-aedf-11e8-88c3-74920022e752.gif)

#### Separate the `front-panel-cuts` and try again 

It seems there is something still "shifts": 

![cut-with-extrude-shifts](https://user-images.githubusercontent.com/6639874/44957927-3b443300-aee1-11e8-8540-cc63aa1fd3aa.gif)


### Broken Visibility Toggling

Since something seems shifted, I give up and 
1. delete the `front-panel-cuts` link and the `Cut` itself. 
2. See the visibility of `panel` is broken: 

![visibility-broken](https://user-images.githubusercontent.com/6639874/44958034-cf62ca00-aee2-11e8-83e5-6b0a80c6240c.gif)

3. Move `panel` out of assembly and the visibility can be toggled again: 

![visibility-fixed](https://user-images.githubusercontent.com/6639874/44958049-0802a380-aee3-11e8-9aa6-a8e71bb23f0f.gif)

### Using sub-shape binder

1. Re-link the `front-panel-cuts` 
2. Create a sub-shape binder for `front-panel-cuts`
3. Cut `panel` with `Binder`
4. An exception is thrown as [`Cannot compute Inventor representation for the shape of Cut.`](https://user-images.githubusercontent.com/6639874/44958332-89f4cb80-aee7-11e8-95f1-ec16597ffce9.gif)
5. Delet the `Cut`, `Binder` etc and re-do the same. 
6. See `Cut` is created as expected. (tip: move `panel` in order to move the `Cut` ATM)
![part-binder-success](https://user-images.githubusercontent.com/6639874/44958491-a5f96c80-aee9-11e8-9e90-ee405066cb20.gif)

### Using nothing but the cut shape itself 

If we move the `front-panel-cut` out of its Assembly Container, it also works just like `Binder`: 

![simple-external-cut](https://user-images.githubusercontent.com/6639874/44958512-11dbd500-aeea-11e8-8fb7-6841eb06c41d.gif)

# Conclusion 

1. There is a visibility toggling issue
2. Why do we need the `Binder` at the moment? 
3. The `front-panel-cut` should reside in project file because it's not related with RaspberryPi itself, it would change from project to project (we might want to prevent exposing 2 usb ports in a model), so how do we create that `front-panel-cut` sketch in the project?

**Comment by realthunder** [comment]
> There is a visibility toggling issue

I am aware of this issue.  There is a potential fix but involves quite significant core changes. I put it to low priority. For an explanation of the cause of the problem, see [here](https://github.com/ceremcem/fc-asm3-cut-window/issues/1). In short, you are in fact seeing the same object appear in more than one coordinate space, and this time they located at the exact same spot. To hide the object in the global coordinate space, select it in the 3D view, and press space. You need to select it twice, to hide both it in both coordinate space.

> Why do we need the Binder at the moment? (can "Cut the panel by using front-panel-cuts" section be fixed?)

Part/PartDesign feature only works when all its tool and base features are inside the same coordinate space. Binder is a way to bring in objects from another coordinate space. In my tutorial, the cut shape, and the USB socket are contained in a sub-assembly, which has its own coordinate space. The binder binds the cut shape, and bring it to the parent assembly at the same location in 3D view. Without the binder, if you directly create a Cut using objects from two different coordinate system, it will be out of place, similar to when you drag an object across different assembly container. My new added feature recalculate the drag object's coordinate and changed its placement so that it appears stationary, binder does the same thing.

> The front-panel-cut should reside in project file because it's not related with RaspberryPi itself

In my tutorial, the cut shape stays with the socket model. The socket and cut shape sub-assembly is then assembled with the PCB in a higher assembly.

> Something still shifts? ("Separate the front-panel-cuts and try again" part)

This is not a regular drag and drop. It does not move any object, but creates a link inside the assembly. I'll see if I can do the same trick on this case. On the other hand, since you are using assembly workbench, you shouldn't rely too much on the manual placement, but use constraint to configure the parts. With the blueprint you showed in the other post, I would create a master sketch to define each components place exactly as shown in the blueprint, and then place each component by as simple PlaneConicident.
