### ISSUE TITLE
issues in PartDesignLinkBranch

### ISSUE THREAD

**Issue by jpg87Fr** [realthunder/FreeCAD_assembly3#491]
I pointed them out in this post :
https://forum.freecadweb.org/viewtopic.php?f=20&t=56295

![pbartDesignLinkBranchIm1](https://user-images.githubusercontent.com/80101333/110106189-a5d3d380-7da9-11eb-8ed4-6e8f2cc0bc30.jpg)
![pbartDesignLinkBranchIm2](https://user-images.githubusercontent.com/80101333/110106195-a79d9700-7da9-11eb-9985-70d6bf3a7387.jpg)

[lv5_jpg87_LinkBranch.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6090031/lv5_jpg87_LinkBranch.zip)

**Comment by ceremcem** [comment]
Is there any particular reason why you don't want to click the "toggle visibility" icon: 


https://user-images.githubusercontent.com/6639874/110120450-1d1b5e80-7dce-11eb-88ef-e9d8b6e63ec5.mp4

**Comment by ceremcem** [comment]
Sorry, the visibility icon can only solve 1 object's visibility issue. Please ignore my previous post.

**Comment by realthunder** [comment]
The Fillet, actually all dress up features (Draft, Chamfer), can only belong to the same solid group of its base. Since you created a new solid when making those two socket, and Fillet is applied on the Mirror which is in another solid, that's why the sockets are not there.

There is indeed a bug here nevertheless. When created the Fillet, it should be auto inserted after the Mirror, instead of at the bottom. I have fixed this problem.

If you want those two socket, then you should delete the Fillet, and turn off `New solid` option in `SlideScrewReceiver`. The recreate the Fillet. With the bug fixed, you won't need to delete the Fillet in the future.

**Comment by oficinerobotica** [comment]
@realthunder would you consider this issue fixed? can it be closed?

**Comment by luzpaz** [comment]
@jpg87Fr please test and report back

**Comment by luzpaz** [comment]
Closing this ticket, @jpg87Fr  
Please re-open if merited.
