### ISSUE TITLE
PartDesign WB bug

### ISSUE THREAD

**Issue by QuakeString** [realthunder/FreeCAD_assembly3#546]
I was following [JOKI ENGINEERING video](https://www.youtube.com/watch?v=d6rzyhQysvc),
the problem start when I try to us "polar pattern" feature. It did not work.
even I've download the JOKO's [FCStd file](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbmNTaVhPZkhJNElkSDBILVlBU0lCc01Qd2hvUXxBQ3Jtc0trMjh1S3h1a015d3k0dWU3OUFITVZDUTRNb09PSzY5TWJ6ZzZRTnlGUThvd294T2ZyWW5EUVpya1htQks2Ymo1a2J3M1plOVJ4b0swVWdxNWEwYVhudW9IeHZNRmw2M0lXMzh6bENQOF9XVHdXUlNvOA&q=https%3A%2F%2Fgrabcad.com%2Flibrary%2Ffreecad-knurling-1) and when I recompute it shows same issue as I'm having with my model.
I'm attaching [My FCStd file](https://drive.google.com/file/d/1R5-yUO4qLSeYHrczqqn2-JXx48bTi5bL/view?usp=sharing), as well.
[Here is video](https://drive.google.com/file/d/1xD_iNSrWqnPFpJYrT5AA4t8zaUc9wp8s/view?usp=sharing) to demonstrate.
![Screenshot_20210329_214528](https://user-images.githubusercontent.com/5375918/112870357-bf7fe680-90db-11eb-9d0c-de9d32e653ad.png)

**Comment by realthunder** [comment]
The problem is caused by performing boolean operation on pattern shapes in parallel. I think OCC has trouble handling this particular parallel cut with multiple helix patterns. Cutting the pattern one by one happens to be fine but slower, which is what upstream FreeCAD is doing. I added a new option to work around the problem, as shown below

![Screenshot from 2021-04-03 17-47-02](https://user-images.githubusercontent.com/1207888/113474886-25d28380-94a5-11eb-8005-e2cefe7ae058.png)
