### ISSUE TITLE
sweeped body destorded after rotation transform

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#563]
Hello, When creating a body with sweep and then the body is transformed using the tool transform, the shape of the final body is distorted.

Before :

![before transform](https://user-images.githubusercontent.com/76944804/113774816-ae5c5880-971f-11eb-887c-e5bc330f8c24.png)

After transform :
![after transform](https://user-images.githubusercontent.com/76944804/113774837-b916ed80-971f-11eb-92aa-853136e2901f.png)
[exemple sweep.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6267458/exemple.sweep.FCStd.zip)

OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.328.22506 +5276 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ff1590e1d7c0aeaf45a29941ec20a10d54cf92ff
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
I think you've attached a different document then the one shown in the screenshot. The problem you have is because you created `Sketch001` using the Sketch workbench button while mapping on some PartDesign feature. This means the sketch is consider an alien feature outside of the body. When the body moves, the sketch will not move with the body hence the error. The correct way to do is to create the sketch using the button in PartDesign workbench as shown below. This will auto add the sketch inside body.

![Screenshot from 2021-04-30 16-40-42](https://user-images.githubusercontent.com/1207888/116670972-f85cf500-a9d2-11eb-83a2-b6912ccdb9f4.png)

**Comment by mwlandolsi** [comment]
Yes that  is :) I'm sorry. 
When sketch added to the body it was solved

At least, I learned some thing new.
https://user-images.githubusercontent.com/76944804/116690270-0ef25480-a9b1-11eb-8076-c51a15ce07f9.mp4

**Comment by mwlandolsi** [comment]
many thanks @realthunder
