### ISSUE TITLE
Understanding the Element Concept

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#61]
While reading https://github.com/realthunder/FreeCAD_assembly3/wiki/Concepts#element, it seems like that: 

Any assembly constraint MUST use two or more of points, edges or faces *directly*. In order to reduce the amount of work on broken reference cases, which might occur when a major change has taken place in the model (like an already assembled component (or even its sub component) would be totally replaced by a totally different one instead of making some small changes) there is a middle layer called "Elements" that holds a map of both **our intention** (ie. "top of the screw") and the actual point/edge/face (ie. "Face017"). When a such major change occurs, we only need to update our intentions. Since we used our "intentions" potentially many times in the actual constraint definitions, our re-work burden would be significantly reduced in such cases. 

### Naming the `Element` instances 

If that's true till this point, we might consider giving names (description of our intention) to the  `Element` instances whenever possible, because If we wanted to replace an object with many elements (like in [Replacing Part example](https://github.com/realthunder/FreeCAD_assembly3/wiki/Replacing-Part)) we can't easily update the broken `Element`s because we can't know/remember what the intention of `Element057` was. Is that true?

[![image](https://user-images.githubusercontent.com/6639874/45105760-adb14f00-b13d-11e8-883e-4ee31ed58397.png)](https://user-images.githubusercontent.com/6639874/45105746-9eca9c80-b13d-11e8-8704-8672712975d6.png)

**Comment by realthunder** [comment]
Yes, you are right. Although, not only big changes like replacing parts, any model changes can possibly break the link. With a deep hierarchical assembly, if there is a breaking Element due to model change, you only need to update the deepest sub-assembly that directly hosting the model object. You can also check out this [tutorial](../wiki/How-to-Handle-Large-Scale-Assembly) and see how elements are manually created for different hierarchies.

**Comment by ceremcem** [comment]
That's a nice concept. Thanks!
