### ISSUE TITLE
[Features Requests] Point on B-spline edge and spline trimming

### ISSUE THREAD

**Issue by YosypC** [realthunder/FreeCAD_assembly3#729]
![Cattura](https://user-images.githubusercontent.com/50027752/125488778-ffc26893-d337-487f-9526-6d2ed6dc2133.PNG)

I guess the picture is self explanatory.
I also need to pad only a section of the exported geometry, but currently I can't trim the B-spline cause I have no point to do so.

**Comment by oficinerobotica** [comment]
The sketcher development is mainly done by Abdulah and this issue might be on the roadmap for solving with the latest sketcher developments https://forum.freecadweb.org/viewtopic.php?f=10&t=51716. It is also a feature that I often need and wish we would have. 

Please make a feature request here: https://forum.freecadweb.org/viewforum.php?f=8 with the title "[Feature request] bspline tangency in sketcher" or other suitable title and I will join the conversation there trying to ping the right people. 

Then we can close this issue here.

**Comment by YosypC** [comment]
Post submitted, waiting moderator approval.
