### ISSUE TITLE
A "cut" feature gave me PAD feature !

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#751]
Hello every body, 
This part is supposed  to be with holes,
![Screenshot from 2021-07-24 20-24-02](https://user-images.githubusercontent.com/76944804/126879250-58754e78-1a77-4dab-8161-3cfacb8f5b84.png)
![Screenshot from 2021-07-24 20-19-15](https://user-images.githubusercontent.com/76944804/126879252-724e0dea-0d79-4b9d-8c7a-42f01c7a1644.png)
[monture.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6872982/monture.FCStd.zip)

**Comment by luzpaz** [comment]
Please always add you full [About](https://wiki.freecadweb.org/About) info

**Comment by mwlandolsi** [comment]
Sorry,
I always add it, but this time i missed it :)
OS: Linux Mint 20.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3627 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: f63a5ea7b459872a3798027df0ff25e776524859
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
The problem happens because the `Refine` operation sometimes reverses the solid. I have just fixed that. The first feature that suffers from this problem is `Pocket`. If you turn off `Two side` rendering, you may discover this problem sooner, with the shape having black faces. Note that, once the problem is fixed, the shape got reversed back, and some your sketch mapping offset may have the wrong orientation. You'll need to adjust that.

![Screenshot from 2021-07-25 14-07-27](https://user-images.githubusercontent.com/1207888/126889495-3cdf7e28-1921-49a8-9967-ea8a10b792df.png)

![Screenshot from 2021-07-25 14-09-16](https://user-images.githubusercontent.com/1207888/126889552-665837cd-e194-4599-8830-dfa9afc6f238.png)

You can turn off two side rendering for all new objects in preference

![Screenshot from 2021-07-25 14-11-12](https://user-images.githubusercontent.com/1207888/126889578-46107b79-e409-4c6d-bf75-76b4dc46c19d.png)

**Comment by mwlandolsi** [comment]
thank you for your answer. pleased to get from you. Waiting next release.

**Comment by mwlandolsi** [comment]
Many thanks, looks good now.
