### ISSUE TITLE
cannot set the color for the python expression window

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD_assembly3#787]
If have looked in every menu and tried all possibilities i could find in the style sheets but i was not able to set the font color for the hovering python expression window. Since use a dark color for the python console background, i cannot read the expression when it is not selected anymore.
![python_expression_window_font_issue](https://user-images.githubusercontent.com/4751351/130331947-30b9b567-481d-4edf-b5f6-0fe101a29f25.gif)

The expression window uses the same background color as the python console. I guess then it should use the same highlighting or font colors.
Furthermore i think the evaluation field on the bottom of the expression window has the wrong background color since it uses the font color(green in my case) of the "python output" / Report View but not the background color of it.

```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

```

**Comment by rmTizi** [comment]
Been chasing this bug for a few days, finally found the cause: 

https://github.com/realthunder/FreeCAD/blob/970eeeee9f7924ea4a3ef0a686df67e7549fa4fc/src/Gui/DlgExpressionInput.cpp#L102

Should be `color:white` instead of black.

In truth there is *a lot* of hard coded colors in that file, leaving little room to style authors to make the formula editor actually readable in alternative color schemes.

Ideally it should at least pull the colors out from the Output window and/or Text Editor user preferences and leave the background colors up the the style sheet.

**Comment by realthunder** [comment]
> Been chasing this bug for a few days, finally found the cause:

@rmTizi Nice fix! Although it's just a blunder mistake, it is very difficult to find. I was actually puzzled myself. Excellent job! 



> Ideally it should at least pull the colors out from the Output window and/or Text Editor user preferences and leave the background colors up the the style sheet.

Yes, true. It can be achieved by exposing those colors as properties like [this](https://github.com/realthunder/FreeCAD/blob/a17b495c3e2be62679d2e526f067ea70c7a8556b/src/Gui/propertyeditor/PropertyEditor.h#L69). The difficult part though is how to deal with style changes where some style has this color specified, but some not. We'll need to somehow track the property setting per stylesheet and supply a sensible default when the property is not set. Do you want to give it a try?
