### ISSUE TITLE
menus in white

### ISSUE THREAD

**Issue by joanperelopez** [realthunder/FreeCAD_assembly3#816]
![Captura de pantalla 2021-09-13 a las 21 06 00](https://user-images.githubusercontent.com/73885181/133142011-1ec8249b-7535-4b26-92bf-305b04669fd2.png)

Go to View -> toolbars or View -> Panels and you will see:

![Captura de pantalla 2021-09-13 a las 20 59 59](https://user-images.githubusercontent.com/73885181/133142050-723df60e-dd47-4026-afe8-239927ba4640.png)

![Captura de pantalla 2021-09-13 a las 21 00 36](https://user-images.githubusercontent.com/73885181/133142095-f3dfa73f-fce5-4fc8-a50e-30305ef49ea3.png)

BR
Pere

**Comment by realthunder** [comment]
Which stylesheet do you use? If it's customized, please post it here. Thanks

**Comment by thomasgi1** [comment]
I think, the problem is that a style sheet is used at all for the Panels and Toolbars sub-menus. If look at the video below, then you see a clear difference in rendering the Workbench sub-menu and the Panels or Toolbars sub-menus.
My style sheet settings are:
- Style sheet: No Style Sheet
- Overlay style sheet: Light-Outline
- View menu style sheet: Light

https://user-images.githubusercontent.com/17226631/133259378-f5df7ec2-0552-4806-b225-62984229beda.mov

**Comment by joanperelopez** [comment]
Solved!
I changed to "No Style Sheet" and it works correctly
Thanks a lot

**Comment by realthunder** [comment]
Do you compiled my branch yourself? Anyway, it is not really solved. I find that MacOSX has trouble showing a checkbox widget in its global menubar. So I just disable it on MacOSX specifically. The one showing now is a normal checkable menu item. The difference is that for normal checkable item, the menu will immediately close when you click any item, while for checkbox, you can click multiple items, which is really convenient when you want to toggle multiple toolbars for instance. You still get the access to the checkbox menu if you right click any toolbar.
