### ISSUE TITLE
Attachment of hole on a flat surface and hole on a cylinder surface is unstable

### ISSUE THREAD

**Issue by ngkz** [realthunder/FreeCAD_assembly3#837]
Attachment of hole on a flat surface and hole on a cylinder surface rotates randomly when fixing or offsetting an element or manipulating other ~~attachment~~constraints.

like this:

![Peek 2021-09-18 17-33](https://user-images.githubusercontent.com/24545581/133882542-4828ab76-40e0-45fb-b95f-fdb0cd407b02.gif)

Both of Stable 2021.09.11 and Daily 2021.09.11 affected by this issue.

File shown in GIF: [debug.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7189505/debug.FCStd.zip)

**Comment by realthunder** [comment]
Fixed in the above commit. Note that the edge you selected is consider an unknown element, because it is not flat. It does not have a well defined orientation. The fix above simply returns an empty rotation as the orientation. 'Undefined' means that the orientation may not align with your visual inspection. A better choice for element is `Sketch002`. After created the element and attachment constraint, you can right click the element to adjust its `Offset` for alignment.
