### ISSUE TITLE
Toggle selectability can't be untoggled.

### ISSUE THREAD

**Issue by ghost** [realthunder/FreeCAD_assembly3#945]
Create two bodies, create an assembly.
Make links from the two bodies and place them in the assembly.

Right-click one of the Links in the 3d-view and choose "Toggle selectability", works as expected. Link can't be selected.

There is no no way to choose "Toggle selectability" again from the right-click menu and changing it in the combo view doesn't have any affect. In the example attached, it made two links not selectable, not just the one I toggled.

Closing and re-opening the file doesn't help.

Using the combo view only to change that setting works ok.

See attached file (.FCStd renamed to .zip), both Link1 and Link2 can't be made to be selectable.

OS: Devuan GNU/Linux 4 (chimaera) (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1

[selectability_test.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7605290/selectability_test.zip)

**Comment by realthunder** [comment]
The `Selectability` is controlled by the `View` property `Selectable`. When you select in the 3D view, you are always selecting the deepest object that actually owns the geometry you picked. So in your case, it is the `Pad001` object. So you are effectively toggling the selectability of `Pad001` which is accessible through both `Link1` and `Link2`. It is the same object, so it may appear that both `Link1` and `Link2` becomes unselectable. But this is the expected behavior. To toggle back, you are supposed to change `Pad001` instead of the link.

To avoid this kind of confusion, I have modified tree view to show special icons for unselectable object.
![Screenshot from 2022-01-01 21-05-52](https://user-images.githubusercontent.com/1207888/147851454-354094ec-e690-4ee7-a066-3674530e63d7.png)

I've also add an action to override selectability setting if you prefer to select in 3D view.
![Screenshot from 2022-01-01 21-17-42](https://user-images.githubusercontent.com/1207888/147851510-06daad57-8bae-4459-afb4-4ebc4b84924c.png)
