### ISSUE TITLE
Sketch is not moving in part design wb

### ISSUE THREAD

**Issue by drom89** [realthunder/FreeCAD_assembly3#949]
Sketch is not moving in part design wb.

![sketch problem](https://user-images.githubusercontent.com/5219063/143960257-e965bd77-26f1-42eb-b2d4-a43028cdaf75.gif)
[vozík.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7621841/vozik.zip)

**Comment by drom89** [comment]
When i deleted all of external geometries it started to work.

**Comment by kevenwyld** [comment]
In the video you can see the red exclamation point on Groove002 which is causing a failure to recompute.  Unfortunately you can't see the failure other than this small red icon because you don't have the status bar or report view turned on.

I opened your file and selected a valid axis for the revolve in Groove002 and everything started to work as expected.

Also for anyone that might try to open the file, it's a winRAR file but the extension is ".zip".

**Comment by drom89** [comment]
You are right. i didnt try to change the axis because it says Invalid shape name not invalid axis or something :).
Thanks
